imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    # translator:      { fallbacks: ["%locale%"] }
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    # form_themes:
    #     - 'KoopaAppBundle:Form:form_div_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Koopa\Bundle\UserBundle\Entity\User
    profile:
        form:
            type: Koopa\Bundle\UserBundle\Form\ProfileType

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

ornicar_gravatar:
    rating: g
    size: 200
    default: mm


knp_paginator:
    page_range: 3                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template


# FOSElasticaSearch
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        serializer: ~
        app:
          finder: ~
          types:
            user:
              mappings:
                username: ~
                firstName: ~
                lastName: ~
                email: ~
              persistence:
                driver: orm
                model: Koopa\Bundle\UserBundle\Entity\User
                provider: ~
                listener: ~
                finder: ~
            parcel:
              mappings:
                houseNumber: ~
                description: ~
                city: ~
                street: ~
                commune: ~
                quarter: ~
              persistence:
                driver: orm
                model: Koopa\Bundle\JobBundle\Entity\Parcel
                provider: ~
                listener: ~
                finder: ~
            job:
              mappings:
                title: ~
                summary: ~
                paymentMethod: ~
                salary: ~
                experience: ~
                skills:
                  type: 'nested'
                  properties:
                    name: ~
                locations:
                  type: 'nested'
                  properties:
                    country: ~
                    town: ~
                subCategories:
                  type: 'nested'
                  properties:
                    name: ~
              persistence:
                driver: orm
                model: Koopa\Bundle\JobBundle\Entity\Job
                provider: ~
                listener: ~
                finder: ~
