<?php

namespace Koopa\Bundle\JobBundle\Repository;

/**
 * ParcelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcelRepository extends \Doctrine\ORM\EntityRepository
{
    public function get($id)
    {
        return $this->find($id);
    }

    /**
     * @param $userId
     * @return array
     */
    public function fetchAllByUser($userId, $getQuery = false)
    {
        $query = $this->_em
            ->createQuery(
                "SELECT p
                FROM KoopaJobBundle:Parcel p
                WHERE p.author = :userId
                ORDER BY p.id ASC"
            )->setParameters(array(
                'userId' => $userId
            ));

        if ($getQuery) {
            return $query;
        }

        return $query->getResult();
    }
}
